"""initial schema

Revision ID: 738d2cfa8423
Revises:
Create Date: 2026-08-21 16:39:48.951553
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "738d2cfa8423"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name_az", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_categories_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(
            "ix_categories_parent_sort", ["parent_id", "sort_order"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_categories_slug"), ["slug"], unique=True)

    op.create_table(
        "otp_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=10), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('console','telegram','email','sms')",
            name=op.f("ck_otp_codes_channel_valid"),
        ),
        sa.CheckConstraint(
            "purpose IN ('login','verify_phone')", name=op.f("ck_otp_codes_purpose_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_codes")),
    )
    with op.batch_alter_table("otp_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_otp_codes_phone"), ["phone"], unique=False)
        batch_op.create_index("ix_otp_lookup", ["phone", "purpose", "expires_at"], unique=False)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("google_id", sa.String(length=64), nullable=True),
        sa.Column("full_name", sa.String(length=120), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("preferred_lang", sa.String(length=2), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin','user')", name=op.f("ck_users_role_valid")),
        sa.CheckConstraint(
            "email IS NOT NULL OR phone IS NOT NULL", name=op.f("ck_users_email_or_phone_present")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_google_id"), ["google_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_phone"), ["phone"], unique=True)

    op.create_table(
        "order_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_no", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new','viewed','completed','cancelled')",
            name=op.f("ck_order_requests_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_order_requests_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_requests")),
    )
    with op.batch_alter_table("order_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_requests_request_no"), ["request_no"], unique=True
        )
        batch_op.create_index("ix_order_requests_status", ["status", "created_at"], unique=False)
        batch_op.create_index("ix_order_requests_user", ["user_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_requests_user_id"), ["user_id"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title_az", sa.String(length=200), nullable=False),
        sa.Column("title_en", sa.String(length=200), nullable=True),
        sa.Column("description_az", sa.Text(), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("old_price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("stock_status", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stock_status IN ('available','out_of_stock','on_order')",
            name=op.f("ck_products_stock_valid"),
        ),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_products_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_products_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_products_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_category_id"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index("ix_products_featured", ["is_featured", "deleted_at"], unique=False)
        batch_op.create_index(
            "ix_products_listing", ["category_id", "deleted_at", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_products_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index("ix_products_price", ["deleted_at", "price_minor"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_slug"), ["slug"], unique=True)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_refresh_tokens_family", ["family_id"], unique=False)
        batch_op.create_index(
            "ix_refresh_tokens_user_expiry", ["user_id", "expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "cart_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity BETWEEN 1 AND 99", name=op.f("ck_cart_items_quantity_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_cart_items_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cart_items_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("user_id", "product_id", name="uq_cart_user_product"),
    )
    with op.batch_alter_table("cart_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cart_items_user_id"), ["user_id"], unique=False)

    op.create_table(
        "order_request_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_request_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("title_snapshot", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price_at_request_minor", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 1", name=op.f("ck_order_request_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_request_id"],
            ["order_requests.id"],
            name=op.f("fk_order_request_items_order_request_id_order_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_request_items_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_request_items")),
    )
    with op.batch_alter_table("order_request_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_request_items_order_request_id"),
            ["order_request_id"],
            unique=False,
        )

    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=600), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("blurhash", sa.String(length=60), nullable=True),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
    )
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.create_index("ix_product_images_order", ["product_id", "sort_order"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_product_images_product_id"), ["product_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_images_product_id"))
        batch_op.drop_index("ix_product_images_order")

    op.drop_table("product_images")
    with op.batch_alter_table("order_request_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_request_items_order_request_id"))

    op.drop_table("order_request_items")
    with op.batch_alter_table("cart_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cart_items_user_id"))

    op.drop_table("cart_items")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index("ix_refresh_tokens_user_expiry")
        batch_op.drop_index("ix_refresh_tokens_family")

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_slug"))
        batch_op.drop_index("ix_products_price")
        batch_op.drop_index(batch_op.f("ix_products_owner_id"))
        batch_op.drop_index("ix_products_listing")
        batch_op.drop_index("ix_products_featured")
        batch_op.drop_index(batch_op.f("ix_products_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_products_category_id"))

    op.drop_table("products")
    with op.batch_alter_table("order_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_requests_user_id"))
        batch_op.drop_index("ix_order_requests_user")
        batch_op.drop_index("ix_order_requests_status")
        batch_op.drop_index(batch_op.f("ix_order_requests_request_no"))

    op.drop_table("order_requests")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_phone"))
        batch_op.drop_index(batch_op.f("ix_users_google_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("settings")
    with op.batch_alter_table("otp_codes", schema=None) as batch_op:
        batch_op.drop_index("ix_otp_lookup")
        batch_op.drop_index(batch_op.f("ix_otp_codes_phone"))

    op.drop_table("otp_codes")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_slug"))
        batch_op.drop_index("ix_categories_parent_sort")
        batch_op.drop_index(batch_op.f("ix_categories_parent_id"))

    op.drop_table("categories")
    # ### end Alembic commands ###
