"""add order request idempotency key

Revision ID: c8a39272abb5
Revises: d3569c540f40
Create Date: 2026-08-21 17:22:19.340223
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c8a39272abb5"
down_revision: str | None = "d3569c540f40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("idempotency_key", sa.String(length=64), nullable=True))
        batch_op.create_index(
            "ix_order_requests_idempotency", ["user_id", "idempotency_key"], unique=False
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "search_text", existing_type=sa.TEXT(), server_default=None, existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "search_text",
            existing_type=sa.TEXT(),
            server_default=sa.text("('')"),
            existing_nullable=False,
        )

    with op.batch_alter_table("order_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_order_requests_idempotency")
        batch_op.drop_column("idempotency_key")

    # ### end Alembic commands ###
