"""add folded search text

Revision ID: d3569c540f40
Revises: 738d2cfa8423
Create Date: 2026-08-21 16:52:38.486029
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d3569c540f40"
down_revision: str | None = "738d2cfa8423"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        # server_default is required: SQLite cannot add a NOT NULL column to a
        # populated table without one.
        batch_op.add_column(sa.Column("search_text", sa.Text(), nullable=False, server_default=""))
        batch_op.create_index("ix_products_search", ["search_text"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index("ix_products_search")
        batch_op.drop_column("search_text")

    # ### end Alembic commands ###
